# Rime schema
# encoding: utf-8

schema:
  schema_id: placeless_flypy
  name: å°é¹¤åŒæ‹¼
  version: "0.1"
  author:
    - double pinyin layout by é¶´
    - Rime schema by ä½›æŒ¯ <chen.sst@gmail.com>
    - Mod by placeless
  description: |
    å°é¹¤åŒæ‹¼è‡ªå®šä¹‰æ–¹æ¡ˆã€‚
  dependencies:
    - moran_english

switches:
  - name: full_shape
    reset: 0
    states: [ åŠè§’, å…¨è§’ ]
  - name: ascii_punct
    states: [ ã€‚ï¼Œ, ï¼ï¼Œ ]

engine:
  processors:
    - recognizer
    - key_binder
    - speller
    - lua_processor@select_character_processor
    - selector
    - punctuator
    - navigator
    - express_editor
  segmentors:
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - script_translator
    # - table_translator@english

speller:
  alphabet: 'zyxwvutsrqponmlkjihgfedcba0987654321,.:!()/-=_+'
  initials: 'Uzyxwvutsrqponmlkjihgfedcba0987654321'
  algebra:
    - erase/^xx$/
    - derive/^([jqxy])u$/$1v/
    - derive/^([aoe])([ioun])$/$1$1$2/
    - xform/^([aoe])(ng)?$/$1$1$2/
    - xform/iu$/Q/
    - xform/(.)ei$/$1W/
    - xform/uan$/R/
    - xform/[uv]e$/T/
    - xform/un$/Y/
    - xform/^sh/U/
    - xform/^ch/I/
    - xform/^zh/V/
    - xform/uo$/O/
    - xform/ie$/P/
    - xform/i?ong$/S/
    - xform/ing$|uai$/K/
    - xform/(.)ai$/$1D/
    - xform/(.)en$/$1F/
    - xform/(.)eng$/$1G/
    - xform/[iu]ang$/L/
    - xform/(.)ang$/$1H/
    - xform/ian$/M/
    - xform/(.)an$/$1J/
    - xform/(.)ou$/$1Z/
    - xform/[iu]a$/X/
    - xform/iao$/N/
    - xform/(.)ao$/$1C/
    - xform/ui$/V/
    - xform/in$/B/
    - xlit/QWRTYUIOPSDFGHJKLZXCVBNM/qwrtyuiopsdfghjklzxcvbnm/

translator:
  dictionary: extended
  prism: placeless_flypy
  contextual_suggestions: true
  max_homophones: 7
  preedit_format:
    - xform/([bpmfdtnljqx])n/$1iao/
    - xform/(\w)g/$1eng/
    - xform/(\w)q/$1iu/
    - xform/(\w)w/$1ei/
    - xform/([dtnlgkhjqxyvuirzcs])r/$1uan/
    - xform/(\w)t/$1ve/
    - xform/(\w)y/$1un/
    - xform/([dtnlgkhvuirzcs])o/$1uo/
    - xform/(\w)p/$1ie/
    - xform/([jqx])s/$1iong/
    - xform/(\w)s/$1ong/
    - xform/(\w)d/$1ai/
    - xform/(\w)f/$1en/
    - xform/(\w)h/$1ang/
    - xform/(\w)j/$1an/
    - xform/([gkhvuirzcs])k/$1uai/
    - xform/(\w)k/$1ing/
    - xform/([jqxnl])l/$1iang/
    - xform/(\w)l/$1uang/
    - xform/(\w)z/$1ou/
    - xform/([gkhvuirzcs])x/$1ua/
    - xform/(\w)x/$1ia/
    - xform/(\w)c/$1ao/
    - xform/([dtgkhvuirzcs])v/$1ui/
    - xform/(\w)b/$1in/
    - xform/(\w)m/$1ian/
    - xform/([aoe])\1(\w)/$1$2/
    - "xform/(^|[ '])v/$1zh/"
    - "xform/(^|[ '])i/$1ch/"
    - "xform/(^|[ '])u/$1sh/"
    - xform/([jqxy])v/$1u/
    - xform/([nl])v/$1Ã¼/
  
english:
  dictionary: moran_english
  enable_completion: true
  enable_sentence: false
  enable_user_dict: true
  initial_quality: 1
  enable_encoder: false
  encode_commit_history: false
  
grammar:
  language: zh-hans-t-essay-bgw

punctuator:
  import_preset: default
  symbols:
    "bq": [ğŸ˜‚ï¸, ğŸ˜…ï¸, ğŸ‰, ğŸ‚, ğŸ˜±ï¸, ğŸ‘Œ, ğŸ˜‡ï¸, ğŸ™ƒï¸, ğŸ¤”ï¸, ğŸ’Šï¸, ğŸ’¯ï¸, ğŸ‘ï¸, ğŸ™ˆï¸, ğŸ’©ï¸, ğŸ˜ˆï¸ ]
    "kb": [âŒ˜, âŒ¥, â‡§, âŒƒ, â‹, â‡ª, ï£¿, âŒ«, âŒ¦, â†©ï¸, â, â†‘, â†“, â†, â†’, â†–, â†˜, â‡Ÿ, â‡]
    "U": [é´±]
  half_shape:
    "\\" : "ã€"
    "#" : "#"
    "@" : "@"
    "~": "~"
    "/": "/"
    "'": {pair: ["ã€Œ", "ã€"]}
    "[": "["
    "]": "]"
    "{": "{"
    "}": "}"
    "*": "*"
    "%": "%"
    "<" : ["<", "ã€Š"]
    ">" : [">", "ã€‹"]

recognizer:
  import_preset: default
  patterns:
    punct: "^(U|bq|kb)$"

menu:
  page_size: 2
  # alternative_select_keys: "';"
  page_down_cycle: true

key_binder:
  bindings:
    - { when: composing, accept: Tab,        send: Page_Down }
    - { when: composing, accept: Shift+Tab,  send: Page_Up }
